sudo: false

addons:
  chrome: stable

language: php
php:
  - "7.1"
  - "7.2"

services:
  - postgresql
  - mysql

env:
  - DB=mysqli
  - DB=pgsql
  - DB=sqlite

before_install:
  # start your web application and listen on `localhost`
  # - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &

before_script:
  - composer install
  - sh -c "if [ '$DB' = 'mysqli' ]; then mysql -u root -e 'drop database if exists phyxo;';fi"
  - sh -c "if [ '$DB' = 'mysqli' ]; then mysql -u root -e 'create database phyxo;';fi"
  - sh -c "if [ '$DB' = 'mysqli' ]; then cp -p local/config/database.inc.mysqli.travis.php local/config/database.inc.php;fi"
  - sh -c "if [ '$DB' = 'pgsql' ]; then psql -c 'drop database if exists phyxo;' -U postgres; fi"
  - sh -c "if [ '$DB' = 'pgsql' ]; then psql -c 'create database phyxo;' -U postgres ;fi"
  - sh -c "if [ '$DB' = 'pgsql' ]; then cp -p local/config/database.inc.pgsql.travis.php local/config/database.inc.php;fi"
  - sh -c "if [ '$DB' = 'sqlite' ]; then rm -f db/phyxo.db;fi"
  - sh -c "if [ '$DB' = 'sqlite' ]; then cp -p local/config/database.inc.sqlite.travis.php local/config/database.inc.php;fi"

  - php tools/install.php
  - php -S 127.0.0.1:1080 -t . &

script:
  - php ./bin/atoum
  # - php ./bin/behat -c behat.travis.yml.dist --suite=web --tags=admin
