sudo: false

# addons:
#   chrome: stable

language: php
php:
  - '7.2'
  - '7.3'
  - '7.4'

services:
  - postgresql
  - mysql

env:
  - DB=mysql
  - DB=pgsql
  - DB=sqlite

# before_install:
#   - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &

before_script:
  - phpenv config-rm xdebug.ini || return 0
  - sh ./tools/prepare.sh
  - composer install

  - sh -c "if [ '$DB' = 'mysql' ]; then mysql -u root -e 'drop database if exists phyxo;';fi"
  - sh -c "if [ '$DB' = 'mysql' ]; then mysql -u root -e 'create database phyxo;';fi"
  - sh -c "if [ '$DB' = 'mysql' ]; then cp -p local/config/.env.mysql.travis .env.local;fi"
  - sh -c "if [ '$DB' = 'pgsql' ]; then psql -c 'drop database if exists phyxo;' -U postgres; fi"
  - sh -c "if [ '$DB' = 'pgsql' ]; then psql -c 'create database phyxo;' -U postgres ;fi"
  - sh -c "if [ '$DB' = 'pgsql' ]; then cp -p local/config/.env.pgsql.travis .env.local;fi"
  - sh -c "if [ '$DB' = 'sqlite' ]; then rm -f db/phyxo.db;fi"
  - sh -c "if [ '$DB' = 'sqlite' ]; then cp -p local/config/.env.sqlite.travis .env.local;fi"

  - php bin/console phyxo:install --db_prefix=phyxo_
  - php bin/console phyxo:user:create --username guest --password '' --mail_address '' --status guest
  - php -S localhost:1080 -t . &

script:
  - php ./bin/atoum
  - php ./bin/behat -c behat.yml.dist --suite=web

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.npm
