install:
  path:  /install.{extension}
  defaults:
    extension: php
  controller: App\Controller\AdminController::install

legacy_home:
  path:  /index.{extension}
  defaults:
    extension: php
  controller: App\Controller\AdminController::index

admin_home:
  path:  /
  controller: App\Controller\AdminController::index
