album:
  path: /category/{category_id}/{start_id}
  controller: App\Controller\AlbumController::album
  defaults:
    start_id: null
  requirements:
    start_id: start-\d+

album_by_params:
  path:  /categories/{extra_params}/{start_id}
  controller: App\Controller\AlbumController::albumByParams
  defaults:
    start_id: null
    extra_params: null
  requirements:
    extra_params: flat
    start_id: start-\d+
