homepage:
  path:  /
  controller: App\Controller\DefaultController::home

about:
  path: /about
  controller: App\Controller\AboutController::index

feed:
  path: /feed.{extension}
  controller: App\Controller\DefaultController::feed
  defaults:
    extension: php

notification:
  path: /notification.{extension}
  controller: App\Controller\DefaultController::notification
  defaults:
    extension: php

comments:
  path: /comments.{extension}
  controller: App\Controller\DefaultController::comments
  defaults:
    extension: php

ws:
  path: /ws.{extension}
  controller: App\Controller\WsController::index
  defaults:
    extension: php

media:
  path: /i.{extension}/{path}-{derivative}{sizes}.{image_extension}
  controller: App\Controller\MediaController::index
  requirements:
    path: '[^_]*'
    derivative: sq|th|2s|xs|sm|me|la|xl|xx|cu
    image_extension: jpg|jpeg
    sizes: '(?:|_[^\.]*)'
  defaults:
    extension: php
    sizes: null

action:
  path: /action.{extension}/{image_id}/{part}/{download}
  controller: App\Controller\DefaultController::action
  defaults:
    extension: php
    download: false
  requirements:
    image_id: \d+
    part: e|r
    download: download
