favorites:
  path: /favorites/{start_id}
  controller: App\Controller\IndexController::favorites
  defaults:
    start_id: null
  requirements:
    start_id: start-\d+

most_visited:
  path: /most_visited/{start_id}
  controller: App\Controller\IndexController::mostVisited
  defaults:
    start_id: null
  requirements:
    start_id: start-\d+

recent_pics:
  path: /recent_pics/{start_id}
  controller: App\Controller\IndexController::recentPics
  defaults:
    start_id: null
  requirements:
    start_id: start-\d+

recent_cats:
  path: /recent_cats/{start_id}
  controller: App\Controller\IndexController::recentCats
  defaults:
    start_id: null
  requirements:
    start_id: start-\d+

best_rated:
  path: /best_rated/{start_id}
  controller: App\Controller\IndexController::bestRated
  defaults:
    start_id: null
  requirements:
    start_id: start-\d+

random:
  path: /random.{extension}
  controller: App\Controller\IndexController::random
  defaults:
    extension: php

random_list:
  path: /list/{list}
  controller: App\Controller\IndexController::randomList
