most_visited:
  path: /most_visited
  controller: App\Controller\IndexController::mostVisited
  defaults:
    start: 0

most_visited__start:
  path: /most_visited/start-{start}
  controller: App\Controller\IndexController::mostVisited
  defaults:
    start: 0
  requirements:
    start: \d+

recent_pics__start:
  path: /recent_pics/start-{start}
  controller: App\Controller\IndexController::recentPics
  defaults:
    start: 0
  requirements:
    start: \d+

recent_pics:
  path: /recent_pics
  controller: App\Controller\IndexController::recentPics
  defaults:
    start: 0

recent_cats__start:
  path: /recent_cats/start-{start}
  controller: App\Controller\CategoryController::recentCats
  defaults:
    start: 0
  requirements:
    start_id: \d+

recent_cats:
  path: /recent_cats
  controller: App\Controller\CategoryController::recentCats
  defaults:
    start: 0

best_rated__start:
  path: /best_rated/start-{start}
  controller: App\Controller\IndexController::bestRated
  defaults:
    start: 0
  requirements:
    start: \d+

best_rated:
  path: /best_rated
  controller: App\Controller\IndexController::bestRated
  defaults:
    start: 0

random:
  path: /random
  controller: App\Controller\IndexController::random

random_list:
  path: /list/{list}
  controller: App\Controller\IndexController::randomList
