# picture_by_tags:
#   path:  /picture.{extension}/{image_id}/tags/{tag_ids}/{start_id}
#   controller: App\Controller\PictureController::picturesByTypes
#   defaults:
#     extension: php
#     start_id: null
#     type: tags
#   requirements:
#     tag_ids: "[^/]+"
#     start_id: start-\d+

picture:
  path:  /picture.{extension}/{image_id}/{type}/{element_id}
  controller: App\Controller\PictureController::picture
  defaults:
    extension: php
  requirements:
    type: category|list|tags|search

picture_by_type:
  path:  /picture.{extension}/{image_id}/{type}/{start_id}
  controller: App\Controller\PictureController::picturesByTypes
  defaults:
    extension: php
    start_id: null
  requirements:
    type: favorites|most_visited|recent_pics|best_rated
    start_id: start-\d+


picture_category_from_calendar:
  path:  /picture.{extension}/{image_id}/category/{category_id}/{extra}
  controller: App\Controller\PictureController::pictureFromCalendar

picture_categories_from_calendar:
  path:  /picture.{extension}/{image_id}/categories/{extra}
  controller: App\Controller\PictureController::pictureFromCalendar
