qsearch:
  path: /qsearch
  controller: App\Controller\SearchController::qsearch

search:
  path: /search
  controller: App\Controller\SearchController::search

search_rules:
  path:  /search_rules/{search_id}
  controller: App\Controller\SearchController::searchRules

search_results:
  path:  /search/{search_id}/{start_id}
  controller: App\Controller\SearchController::searchResults
  defaults:
    start_id: null
  requirements:
    start_id: start-\d+
