qsearch:
  path: /qsearch
  controller: App\Controller\SearchController::qsearch

search:
  path: /search
  controller: App\Controller\SearchController::search

search_rules:
  path:  /search_rules/{search_id}
  controller: App\Controller\SearchController::searchRules

search_results__start:
  path:  /search/{search_id}/start-{start}
  controller: App\Controller\SearchController::searchResults
  defaults:
    start: 0
  requirements:
    start: \d+
    search_id: \d+

# same as search_results__start without start param
search_results:
  path:  /search/{search_id}
  controller: App\Controller\SearchController::searchResults
  defaults:
    start: 0
  requirements:
    search_id: \d+
