tags:
  path: /tags/{display_mode}
  controller: App\Controller\TagController::list
  defaults:
    display_mode: letters
  requirements:
    display_mode: cloud|letters

images_by_tags__start:
  path: /tags/{tag_ids}/start-{start}
  controller: App\Controller\TagController::imagesByTags
  defaults:
    start: 0
  requirements:
    tag_ids: .+
    start: \d+

# same as images_by_tags__start without start param
images_by_tags:
  path: /tags/{tag_ids}
  controller: App\Controller\TagController::imagesByTags
  defaults:
    start: 0
  requirements:
    tag_ids: .+
