register:
  path: /register.{extension}
  controller: App\Controller\SecurityController::register
  defaults:
    extension: php

reset_password:
  path: /password.{extension}/{activation_key}
  controller: App\Controller\SecurityController::resetPassword
  defaults:
    extension: php

forgot_password:
  path: /password.{extension}
  controller: App\Controller\SecurityController::forgotPassword
  defaults:
    extension: php

login:
  path: /identification.{extension}
  controller: App\Controller\SecurityController::login
  defaults:
    extension: php

logout:
  path: /logout
  controller: App\Controller\SecurityController::logout

profile:
  path: /profile.{extension}
  controller: App\Controller\SecurityController::profile
  defaults:
    extension: php
