register:
  path: /register
  controller: App\Controller\SecurityController::register

reset_password:
  path: /password/{activation_key}
  controller: App\Controller\SecurityController::resetPassword

forgot_password:
  path: /password
  controller: App\Controller\SecurityController::forgotPassword

login:
  path: /identification
  controller: App\Controller\SecurityController::login

logout:
  path: /logout
  controller: App\Controller\SecurityController::logout

profile:
  path: /profile
  controller: App\Controller\SecurityController::profile
