register:
  path: /register.{extension}
  controller: App\Controller\UserController::register
  defaults:
    extension: php

password:
  path: /password.{extension}
  controller: App\Controller\UserController::password
  defaults:
    extension: php

login:
  path: /identification.{extension}
  controller: App\Controller\SecurityController::login
  defaults:
    extension: php

logout:
  path: /logout
  controller: App\Controller\SecurityController::logout

profile:
  path: /profile.{extension}
  controller: App\Controller\UserController::profile
  defaults:
    extension: php
