# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    legacy_base_dir: '%kernel.project_dir%/src/LegacyPages'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        public:
            false # Allows optimizing the container by removing unused services; this also means
            # fetching services directly from the container via $container->get() won't work.
            # The best practice is to be explicit about your dependencies anyway.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php,Phyxo,LegacyPages}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    Phyxo\DBLayer\DBLayer:
        factory: 'Phyxo\DBLayer\DBLayer::initFromDSN'
        arguments: ['%env(DATABASE_URL)%']

    phyxo.conn:
        public: true
        alias: 'Phyxo\DBLayer\DBLayer'

    App\DataCollector\DBLayerCollector:
        tags:
            - name: data_collector
              template: 'data_collector/queries.html.twig'
              id: 'app.dblayer_collector'
              public: false

    Phyxo\Template\Template:
        factory: 'Phyxo\Template\Template::init'
        arguments: ['%kernel.cache_dir%/smarty']

    phyxo.template:
        public: true
        alias: 'Phyxo\Template\Template'

    Phyxo\Conf: ~
    phyxo.conf:
        public: true
        alias: 'Phyxo\Conf'
