framework:
  csrf_protection: ~
  session:
    handler_id: Phyxo\DBLayer\SessionHandler

services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  App\Security\LoginFormAuthenticator:
    autowire: true
    autoconfigure: true

  Phyxo\DataCollector\DBLayerCollector:
    tags:
      - name: data_collector
        template: 'data_collector/queries.html.twig'
        id: 'app.dblayer_collector'

  Phyxo\DataCollector\SmartyCollector:
    tags:
      - name: data_collector
        template: 'data_collector/smarty.html.twig'
        id: 'app.smarty_collector'

  Phyxo\DBLayer\SessionHandler: ~

  App\Command\UserCreateCommand:
    autoconfigure: true

  App\Command\UserListCommand:
    autoconfigure: true
