admin_batch_manager_global:
  path: /batch/global/{filter}
  controller: App\Controller\Admin\BatchManagerController:global
  defaults:
    filter: null
    start: 0
  requirements:
    filter: caddie|favorites|last_import|no_album|no_tag|duplicates|all_photos

admin_batch_manager_global__start:
  path: /batch/global/{start}/{filter}
  controller: App\Controller\Admin\BatchManagerController:global
  defaults:
    filter: null
  requirements:
    filter: caddie|favorites|last_import|no_album|no_tag|duplicates|all_photos
    start: \d+

admin_batch_manager_global_empty_caddie:
  path: /batch/global/empty_caddie/{start}
  controller: App\Controller\Admin\BatchManagerController:emptyCaddie
  defaults:
    start: 0
  requirements:
    start: \d+

admin_batch_manager_unit:
  path: /batch/unit/{filter}
  controller: App\Controller\Admin\BatchManagerController:unit
  defaults:
    filter: null
    start: 0
  requirements:
    filter: caddie|favorites|last_import|no_album|no_tag|duplicates|all_photos

admin_batch_manager_unit__start:
  path: /batch/unit/{start}/{filter}
  controller: App\Controller\Admin\BatchManagerController:unit
  defaults:
    filter: null
  requirements:
    filter: caddie|favorites|last_import|no_album|no_tag|duplicates|all_photos
    start: \d+
