install:
  path: /install/{step}
  controller: App\Controller\InstallController::index
  defaults:
    step: language
  requirements:
    step: language|check|database|user|success

legacy_home:
  path: /index.{extension}
  controller: App\Controller\AdminController::index
  defaults:
    extension: php

admin_upgrade:
  path: /upgrade
  controller: App\Controller\AdminController::upgrade

admin_check_upgrade:
  path: /check_upgrade
  controller: App\Controller\Admin\DashboardController::index
  defaults:
    check_upgrade: true

admin_home:
  path: /
  controller: App\Controller\Admin\DashboardController::index
  defaults:
    check_upgrade: false

admin_menubar:
  path: /menubar
  controller: App\Controller\Admin\MenubarController:index

admin_menubar_update:
  path: /menubar/update
  controller: App\Controller\Admin\MenubarController:update
  methods: POST
