admin_notification:
  path: /notification
  controller: App\Controller\Admin\NotificationController:params

admin_notification_subscribe:
  path: /notification/subscribe
  controller: App\Controller\Admin\NotificationController:subscribe

admin_notification_send:
  path: /notification/send
  controller: App\Controller\Admin\NotificationController:send
