admin_photo:
  path: /photo/{image_id}/{category_id}
  controller: App\Controller\Admin\PhotoController:edit
  defaults:
    category_id: null
  requirements:
    image_id: \d+
    category_id: \d+

admin_photo_delete:
  path: /photo/{image_id}/delete/{category_id}
  controller: App\Controller\Admin\PhotoController:delete
  methods: ['POST']
  defaults:
    category_id: null
  requirements:
    image_id: \d+
    category_id: \d+

admin_photo_sync_metadata:
  path: /photo/{image_id}/sync/{category_id}
  controller: App\Controller\Admin\PhotoController:syncMetadata
  defaults:
    category_id: null
  requirements:
    image_id: \d+
    category_id: \d+

admin_photo_coi:
  path: /photo/{image_id}/coi/{category_id}
  controller: App\Controller\Admin\PhotoController:coi
  defaults:
    category_id: null
  requirements:
    image_id: \d+
    category_id: \d+
