admin_tags:
  path: /tags
  controller: App\Controller\Admin\TagsController:list

admin_tags_actions:
  path: /tags/actions
  controller: App\Controller\Admin\TagsController:actions
  methods: ['POST']

admin_tags_add:
  path: /tags/add
  controller: App\Controller\Admin\TagsController:add
  methods: ['POST']

admin_tags_permissions:
  path: /tags/permissons
  controller: App\Controller\Admin\TagsController:permissions

admin_tags_pending:
  path: /tags/pending
  controller: App\Controller\Admin\TagsController:pending

admin_tags_delete_orphans:
  path: /tags/delete_orphans
  controller: App\Controller\Admin\TagsController:deleteOrphans
