admin_update:
  path: /update/{step}
  controller: App\Controller\Admin\UpdateController:core
  defaults:
    step: 0
  requirements:
    step: \d+

admin_update_extensions:
  path: /update/extensions
  controller: App\Controller\Admin\UpdateController:extensions
